//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rolodex_Contacts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Info
    {
        public System.Guid Id { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> uni_id { get; set; }
    
        public virtual Contact_Names Contact_Names { get; set; }
    }
}
