//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rolodex_Contacts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Names
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact_Names()
        {
            this.Contact_Info = new HashSet<Contact_Info>();
        }
    
        public System.Guid Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string orderDate { get; set; }
        public System.Guid key { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact_Info> Contact_Info { get; set; }
    }
}
